Ai.Lpnu/Models/AppUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ai.Lpnu.Models
{
    public class AppUser : Raven.Identity.IdentityUser
    {
        /// <summary>
        /// A user's full name.
        /// </summary>
        public string FullName { get; set; }
    }
}

Ai.Lpnu/Models/ErrorViewModel.cs
using System;

namespace Ai.Lpnu.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ai.Lpnu/Models/RegisterModel.cs
namespace Ai.Lpnu.Models
{
    public class RegisterModel
    {
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }
}

Ai.Lpnu/Models/SignInModel.cs
namespace Ai.Lpnu.Models
{
    public class SignInModel
    {
        public string Login { get; set; }
        public string Password { get; set; }
    }
}

Ai.Lpnu/Controllers/AdminController.cs
using Ai.Lpnu.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Ai.Lpnu.Controllers
{
    [Authorize]
    public class AdminController: Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ai.Lpnu/Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Ai.Lpnu.Controllers
{
    public class AppsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Generic()
        {
            return View();
        }

        public IActionResult Elements()
        {
            return View();
        }
    }
}

Ai.Lpnu/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Raven.Client.Documents.Session;
using System;

using System.Threading.Tasks;

namespace Ai.Lpnu.Controllers
{
    public class BaseController : Controller
    {
        public BaseController(IAsyncDocumentSession dbSession)
        {
            this.DbSession = dbSession;

            // RavenDB best practice: during save, wait for the indexes to update.
            // This way, Post-Redirect-Get scenarios won't be affected by stale indexes.
            // For more info, see https://ravendb.net/docs/article-page/4.2/csharp/client-api/session/saving-changes
            this.DbSession.Advanced.WaitForIndexesAfterSaveChanges(timeout: TimeSpan.FromSeconds(5), throwOnTimeout: false);
        }

        public IAsyncDocumentSession DbSession { get; private set; }

        /// <summary>
        /// Executes the action. If no error occurred, any changes made in the RavenDB document session will be saved.
        /// </summary>
        /// <param name="context"></param>
        /// <param name="next"></param>
        /// <returns></returns>
        public override async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
        {
            var executedContext = await next.Invoke();
            if (executedContext.Exception == null)
            {
                await DbSession.SaveChangesAsync();
            }
        }
    }
}

Ai.Lpnu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ai.Lpnu.Models;

namespace Ai.Lpnu.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ai.Lpnu/Controllers/LoginController.cs
using Ai.Lpnu.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Raven.Client.Documents.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ai.Lpnu.Controllers
{
    public class LoginController: BaseController
    {
        private readonly SignInManager<AppUser> signInManager;
        private readonly UserManager<AppUser> userManager;

        public LoginController(
            IAsyncDocumentSession dbSession, // injected thanks to Startup.cs call to services.AddRavenDbAsyncSession()
            UserManager<AppUser> userManager, // injected thanks to Startup.cs call to services.AddRavenDbIdentity<AppUser>()
            SignInManager<AppUser> signInManager) // injected thanks to Startup.cs call to services.AddRavenDbIdentity<AppUser>()
            : base(dbSession)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignIn([FromForm]SignInModel model)
        {
            string reason = string.Empty;
            try
            {
                var user = (await DbSession.Advanced.LoadStartingWithAsync<AppUser>("AppUsers")).First();
                if (user.UserName == model.Login)
                {
                    var signInResult = await this.signInManager.PasswordSignInAsync(user.Email, model.Password, true, false);
                    if (signInResult.Succeeded)
                    {
                        return RedirectToAction("Index", "Admin");
                    }
                    reason = signInResult.IsLockedOut ? "Your user is locked out" :
                    signInResult.IsNotAllowed ? "Your user is not allowed to sign in" :
                    signInResult.RequiresTwoFactor ? "2FA is required" : "";
                }
                else
                {
                    reason = "Bad user name or password";
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
            }

            return RedirectToAction("SignInFailure", new { reason });
        }

        [HttpGet]
        public IActionResult SignInFailure(string reason)
        {
            ViewBag.FailureReason = reason;
            return View();
        }
      

        [HttpGet]
        public IActionResult ChangeRoles()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromBody]RegisterModel model)
        {
            // Create the user.
            var appUser = new AppUser
            {
                Email = model.Email,
                UserName = model.Login
            };
            try
            {
                var createUserResult = await this.userManager.CreateAsync(appUser, model.Password);
                if (!createUserResult.Succeeded)
                {
                    var errorString = string.Join(", ", createUserResult.Errors.Select(e => e.Description));
                    return RedirectToAction("RegisterFailure", new { reason = errorString });
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
            }


            // Sign him in and go home.
            await this.signInManager.SignInAsync(appUser, true);
            return this.RedirectToAction("Index", "Admin");
        }

        [HttpGet]
        public async Task<IActionResult> SignOut()
        {
            await this.signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

Ai.Lpnu/Views/Admin/Index.cshtml
ADMIN

Ai.Lpnu/Views/Apps/Generic.cshtml
@{
    ViewData["Title"] = "Generic";
    Layout = "~/Views/Apps/_Layout2.cshtml";
}

<!-- Start about Area -->
<section class="about-area section-gap">
    <div class="container">
        <div class="row justify-content-center align-items-center d-flex">
            <div class="col-lg-6 about-left">
                <h1>
                    We Believe that <br>
                    Interior beautifies the <br>
                    Total Architecture
                </h1>
                <p class="mt-20">
                    inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that, as women, our behavior on the job is beyond reproach. inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that.
                </p>
                <a href="#" class="btn primary-btn text-uppercase mt-20">see details</a>
            </div>
            <div class="col-lg-6 about-right">
                <img class="img-fluid" src="~/template/apps/img/about-img.png" alt="">
            </div>
        </div>
    </div>
</section>
<!-- End about Area -->
<!-- Start Generic Area -->
<section class="about-generic-area section-gap">
    <div class="container border-top-generic">
        <h3 class="about-title mb-30">Elaboration about Generic Page</h3>
        <div class="row">
            <div class="col-md-12">
                <div class="img-text">
                    <p>Recently, the US Federal government banned online casinos from operating in America by making it illegal to transfer money to them through any US bank or payment system. As a result of this law, most of the popular online casino networks such as Party Gaming and PlayTech left the United States. Overnight, online casino players found themselves being chased by the Federal government. But, after a fortnight, the online casino industry came up with a solution and new online casinos started taking root. These began to operate under a different business umbrella, and by doing that, rendered the transfer of money to and from them legal. A major part of this was enlisting electronic banking systems that would accept this new clarification and start doing business with me. Listed in this article are the electronic banking systems that accept players from the United States that wish to play in online casinos.</p>
                </div>
            </div>
            <div class="col-lg-12">
                <p>Recently, the US Federal government banned online casinos from operating in America by making it illegal to transfer money to them through any US bank or payment system. As a result of this law, most of the popular online casino networks such as Party Gaming and PlayTech left the United States. Overnight, online casino players found themselves being chased by the Federal government. But, after a fortnight, the online casino industry came up with a solution and new online casinos started taking root. These began to operate under a different business umbrella, and by doing that, rendered the transfer of money to and from them legal. A major part of this was enlisting electronic banking systems that would accept this new clarification and start doing business with me. Listed in this article are the electronic banking systems that accept players from the United States that wish to play in online casinos.</p>
            </div>
            <div class="col-lg-12">
                <p>Recently, the US Federal government banned online casinos from operating in America by making it illegal to transfer money to them through any US bank or payment system. As a result of this law, most of the popular online casino networks such as Party Gaming and PlayTech left the United States. Overnight, online casino players found themselves being chased by the Federal government. But, after a fortnight, the online casino industry came up with a solution and new online casinos started taking root. These began to operate under a different business umbrella, and by doing that, rendered the transfer of money to and from them legal. A major part of this was enlisting electronic banking systems that would accept this new clarification and start doing business with me. Listed in this article are the electronic banking systems that accept players from the United States that wish to play in online casinos.</p>
            </div>
            <div class="col-md-12">
                <div class="img-text">
                    <p>Recently, the US Federal government banned online casinos from operating in America by making it illegal to transfer money to them through any US bank or payment system. As a result of this law, most of the popular online casino networks such as Party Gaming and PlayTech left the United States. Overnight, online casino players found themselves being chased by the Federal government. But, after a fortnight, the online casino industry came up with a solution and new online casinos started taking root. These began to operate under a different business umbrella, and by doing that, rendered the transfer of money to and from them legal. A major part of this was enlisting electronic banking systems that would accept this new clarification and start doing business with me. Listed in this article are the electronic banking systems that accept players from the United States that wish to play in online casinos.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Generic Start -->

Ai.Lpnu/Views/Apps/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>AI</title>
    <link rel="shortcut icon" href="~/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="~/template/apps/css/linearicons.css">
    <link rel="stylesheet" href="~/template/apps/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/template/apps/css/bootstrap.css">
    <link rel="stylesheet" href="~/template/apps/css/magnific-popup.css">
    <link rel="stylesheet" href="~/template/apps/css/owl.carousel.css">
    <link rel="stylesheet" href="~/template/apps/css/hexagons.min.css">
    <link rel="stylesheet" href="~/template/apps/css/main.css">
</head>
<body>
    <!-- start banner Area -->
    <section class="banner-area" id="home">
        <!-- Start Header Area -->
        @await Html.PartialAsync("_header")
        <!-- End Header Area -->
        <div class="container">
            <div class="row justify-content-end fullscreen align-items-center">
                <div class="col-lg-6 col-md-12 banner-left">
                    <h1 class="text-white">
                        @Localizer["Department1"] <br>
                        @Localizer["Department2"]
                    </h1>
                    <p class="mx-auto text-white  mt-20 mb-40">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp <br> or incididunt ut labore et dolore magna aliqua. Ut enim ad minim.
                    </p>
                </div>
                <div class="col-lg-6 col-md-12 no-padding banner-right">
                    <img class="img-fluid" src="~/template/apps/img/ai-img.svg" alt="">
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->
    @RenderBody()
    <!-- start footer Area -->
    @await Html.PartialAsync("_footer")
    <!-- End footer Area -->
    <script src="~/template/apps/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="~/template/apps/js/vendor/bootstrap.min.js"></script>
    <script src="~/template/apps/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/template/apps/js/jquery.magnific-popup.min.js"></script>
    <script src="~/template/apps/js/parallax.min.js"></script>
    <script src="~/template/apps/js/owl.carousel.min.js"></script>
    <script src="~/template/apps/js/jquery.sticky.js"></script>
    <script src="~/template/apps/js/hexagons.min.js"></script>
    <script src="~/template/apps/js/jquery.counterup.min.js"></script>
    <script src="~/template/apps/js/waypoints.min.js"></script>
    <script src="~/template/apps/js/main.js"></script>
</body>
</html>

Ai.Lpnu/Views/Apps/_Layout2.cshtml
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Apps</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="~/template/apps/css/linearicons.css">
    <link rel="stylesheet" href="~/template/apps/css/owl.carousel.css">
    <link rel="stylesheet" href="~/template/apps/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/template/apps/css/nice-select.css">
    <link rel="stylesheet" href="~/template/apps/css/magnific-popup.css">
    <link rel="stylesheet" href="~/template/apps/css/bootstrap.css">
    <link rel="stylesheet" href="~/template/apps/css/main.css">
</head>
<body>
    <!-- Start banner Area -->
    <section class="generic-banner relative">
        <!-- Start Header Area -->
        @await Html.PartialAsync("_header")
        <!-- End Header Area -->
        <div class="container">
            <div class="row height align-items-center justify-content-center">
                <div class="col-lg-10">
                    <div class="generic-banner-content">
                        <h2 class="text-white text-center">The Generic Page</h2>
                        <p class="text-white">It won’t be a bigger problem to find one video game lover in your <br> neighbor. Since the introduction of Virtual Game.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->
    <!-- About Generic Start -->
    <div class="main-wrapper">
        @RenderBody()
        <!-- start footer Area -->
        @await Html.PartialAsync("_footer")
        <!-- End footer Area -->
    </div>
    <script src="~/template/apps/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="~/template/apps/js/vendor/bootstrap.min.js"></script>
    <script src="~/template/apps/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/template/apps/js/jquery.magnific-popup.min.js"></script>
    <script src="~/template/apps/js/parallax.min.js"></script>
    <script src="~/template/apps/js/owl.carousel.min.js"></script>
    <script src="~/template/apps/js/jquery.sticky.js"></script>
    <script src="~/template/apps/js/hexagons.min.js"></script>
    <script src="~/template/apps/js/jquery.counterup.min.js"></script>
    <script src="~/template/apps/js/waypoints.min.js"></script>
    <script src="~/template/apps/js/main.js"></script>
</body>
</html>

Ai.Lpnu/Views/Apps/_Layout3.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Apps</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="~/template/apps/css/linearicons.css">
    <link rel="stylesheet" href="~/template/apps/css/owl.carousel.css">
    <link rel="stylesheet" href="~/template/apps/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/template/apps/css/nice-select.css">
    <link rel="stylesheet" href="~/template/apps/css/magnific-popup.css">
    <link rel="stylesheet" href="~/template/apps/css/bootstrap.css">
    <link rel="stylesheet" href="~/template/apps/css/main.css">
</head>
<body>
    <!-- Start banner Area -->
    <section class="generic-banner relative">
        <!-- Start Header Area -->
        @await Html.PartialAsync("_header")
        <!-- End Header Area -->
        <div class="container">
            <div class="row height align-items-center justify-content-center">
                <div class="col-lg-10">
                    <div class="generic-banner-content">
                        <h2 class="text-white text-center">The Elements Page</h2>
                        <p class="text-white">It won’t be a bigger problem to find one video game lover in your <br> neighbor. Since the introduction of Virtual Game.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->
    @RenderBody()
    <!-- start footer Area -->
    @await Html.PartialAsync("_footer")
    <!-- End footer Area -->

    <script src="~/template/apps/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="~/template/apps/js/vendor/bootstrap.min.js"></script>
    <script src="~/template/apps/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/template/apps/js/jquery.magnific-popup.min.js"></script>
    <script src="~/template/apps/js/parallax.min.js"></script>
    <script src="~/template/apps/js/owl.carousel.min.js"></script>
    <script src="~/template/apps/js/jquery.sticky.js"></script>
    <script src="~/template/apps/js/hexagons.min.js"></script>
    <script src="~/template/apps/js/jquery.counterup.min.js"></script>
    <script src="~/template/apps/js/jquery.nice-select.min.js"></script>
    <script src="~/template/apps/js/waypoints.min.js"></script>
    <script src="~/template/apps/js/main.js"></script>
</body>
</html>

Ai.Lpnu/Views/Apps/_footer.cshtml
<footer class="footer-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-12">
                <div class="single-footer-widget">
                    <h6>Top Products</h6>
                    <ul class="footer-nav">
                        <li><a href="#">Managed Website</a></li>
                        <li><a href="#">Manage Reputation</a></li>
                        <li><a href="#">Power Tools</a></li>
                        <li><a href="#">Marketing Service</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6  col-md-12">
                <div class="single-footer-widget newsletter">
                    <h6>Newsletter</h6>
                    <p>You can trust us. we only send promo offers, not a single spam.</p>
                    <div id="mc_embed_signup">
                        <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">
                            <div class="form-group row" style="width: 100%">
                                <div class="col-lg-8 col-md-12">
                                    <input name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
                                    <div style="position: absolute; left: -5000px;">
                                        <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                    </div>
                                </div>

                                <div class="col-lg-4 col-md-12">
                                    <button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
                                </div>
                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-12">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">Instragram Feed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="~/template/apps/img/i1.jpg" alt=""></li>
                        <li><img src="~/template/apps/img/i2.jpg" alt=""></li>
                        <li><img src="~/template/apps/img/i3.jpg" alt=""></li>
                        <li><img src="~/template/apps/img/i4.jpg" alt=""></li>
                        <li><img src="~/template/apps/img/i5.jpg" alt=""></li>
                        <li><img src="~/template/apps/img/i6.jpg" alt=""></li>
                        <li><img src="~/template/apps/img/i7.jpg" alt=""></li>
                        <li><img src="~/template/apps/img/i8.jpg" alt=""></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row footer-bottom d-flex justify-content-between">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            <p class="col-lg-8 col-sm-12 footer-text m-0 text-white">
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            </p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            <div class="col-lg-4 col-sm-12 footer-social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
            </div>
        </div>
    </div>
</footer>

Ai.Lpnu/Views/Apps/_header.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<header class="default-header">
    <nav class="navbar navbar-expand-lg  navbar-light">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Apps")">
                <img src="~/images/logo1.png" alt="">
                @Localizer["Department"]
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="lnr lnr-menu"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end align-items-center" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li><a href="@Url.Action("Index", "Apps")#home">@Localizer["Home"]</a></li>
                    <li><a href="@Url.Action("Index", "Apps")#feature">@Localizer["Feature"]</a></li>
                    <li><a href="@Url.Action("Index", "Apps")#news">@Localizer["News"]</a></li>
                    <li><a href="@Url.Action("Index", "Apps")#price">@Localizer["About"]</a></li>
                    <li><a href="@Url.Action("Index", "Apps")#faq">@Localizer["FAQ"]</a></li>
                    <!-- Dropdown -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            @Localizer["Pages"]
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="@Url.Action("Generic", "Apps")">Generic</a>
                            <a class="dropdown-item" href="@Url.Action("Elements", "Apps")">Elements</a>
                        </div>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            @Localizer["Lang"]
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="\?culture=en">En</a>
                            <a class="dropdown-item" href="\?culture=uk">Ua</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Ai.Lpnu/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>